:linkcss:
:stylesdir: css
:stylesheet: mystyle.css
:twoinches: width='360'
:full-width: width='100%'
:three-quarters-width: width='75%'
:two-thirds-width: width='66%'
:half-width: width='50%'
:half-size:
:one-thirds-width: width='33%'
:one-quarters-width: width='25%'
:thumbnail: width='60'
:imagesdir: images
:sourcesdir: codes
:icons: font
:hide-uri-scheme!:
:figure-caption: 図
:example-caption: リスト
:table-caption: 表
:appendix-caption: 付録
:xrefstyle: short
:section-refsig:
:chapter-refsig:

NOTE: 下記文章中では、ワークスペースとして `Users\kuboaki\rubybok` といった場所を指定していますが、これは、みなさんがCloneしたリポジトリのディレクトリ名で読み替えてください。


[[setup_text_editor]]
= テキストエディターを設定する

プログラミングは、多くの文字を打ち込む作業です。そんなプログラマにとって、プログラムを入力するために使う道具は、料理人の包丁、美容師のハサミにも匹敵する重要な道具です。
そのため、ほとんどのプログラマは、プログラムを書くのに便利な機能を持ったお気に入りのアプリケーションを使います。そのようなアプリケーションは、テキストエディターとかプログラミングエディタと呼ばれています（短くエディタと呼ぶことが多いです）。

みなさんが、まだプログラミング用のテキストエディターを用意していないようなら、ここで準備しておきましょう。


== テキストエディターはプログラミングに必須

プログラミングは、通常の文章の入力に比べると、たくさんのカーソルの移動、テキストの一部の切り貼り（カット＆ペースト）、検索や置換を使います。
そのため、入力や操作の軽快さが重要になってきます。
文字列の入力やカーソルの移動がスムーズにできないと、プログラムを作っているときに思考のリズムが乱れてしまうからです。

Windowsのメモ帳やMacのテキストエディットでも、プログラムを編集しようと思えばできます。
しかし、プログラムの予約語の誤りや構文の小さなミスを発見するのにも、テキストエディターを使うときよりも時間がかかってしまうでしょう。
つまり、プログラムの編集にはあまり適していないのです。

一方、テキストエディターは、プログラミング向けに <<editor_functions>> のような機能を提供しています。


[[editor_functions]]
.プログラム開発に使うテキストエディターの機能
[example]
--
* プログラム言語の種類による予約語の色分け（シンタックスハイライト）
* 入力の補完（コンプリーション）
* 外部アプリケーションとの連携
* 自動的に字下げを支援する（オートインデント）
* 多数のキーボードショートカットによるマウス利用の回避
--

このほかにも、プログラマの作業に向くよう、軽快な入力とよく使う操作を簡便に利用する工夫を数多く提供しています。


== 自分が使うテキストエディターを決めよう

もし、すでにインストールされていたり使っているエディタがある人はそれを使うとよいでしょう。
まだ定まったテキストエディターを持っていない人は、この機会にインストールして、使えるようになってしまいましょう。

まだ決まったエディタを使っていない人は、身近な友人や同僚が使っているものを選ぶとよいでしょう。
無料で使えるものから、私がおすすめするエディタを <<recommended_editors>> に挙げておきます。


[[recommended_editors]]
.おすすめのテキストエディター
[cols="25%,75%"]
|===
2+h| Windows、Mac用、linux用
| Visual Studio Code | `https://azure.microsoft.com/ja-jp/products/visual-studio-code/`
| Vim | `http://www.vim.org/`
| Emacs | `http://www.gnu.org/software/emacs/emacs.html`
2+h| Windows、Mac用
| Atom | `https://atom.io/`
| Brackets | `http://brackets.io/`
2+h| Windows用
| Notepad++ | `https://notepad-plus-plus.org/`
| xyzzy | `https://xyzzy-022.github.io/`
2+h| Mac用
| CotEditor | `https://apps.apple.com/app/coteditor/`
|===

それぞれのエディタの導入方法、機能、使い方については、Webサイトやその他のページを参照してください。

ところで、WindowsでもMacでも使えるエディタが多いのに気づいたでしょうか。こういうエディタならば、PCからMacに乗り換えたときでも同じエディタが使えますね。


== テキストエディターに慣れておこう


このあとのRubyのインストール作業でも、プログラミングでも、テキストファイルを編集することが基本になります。そのときは、みなさんが選んだテキストエディターを使って編集することになるでしょう。

みなさんがどのエディタを選ぶとしても、最初に注意しておくことがあります。それは、テキストエディターは「GUIアプリケーションではない」ということです。
基本的にキーボードからのキー操作によって使うものです。
このことは、普段はアプリケーションをマウスで操作している人、とりわけタイピングに慣れていない人にってとっては、最初は煩わしいこと感じるでしょう。
それだけに、普段から使って慣れておくことが大切です。

== タイピングに慣れておこう

ある大学の講義でプログラミング演習をやったときのことです。演習についてこれない学生のほとんどは、やっている内容がわからないのではなく、それ以前に入力が遅くてついてこれないのだということがわかりました。

そこで、タイピングが不得手な人は、並行してタイピングを練習することを強くお勧めします。タイピングの練習についてはWebサイトやアプリケーションがたくさんあるので、探してみましょう。
コツは一時期にまとまった時間で練習するのではなく「毎日10分だけ、でも毎日練習する」「指導方法を守ってゆっくりでよいから確実に」「早く打とうとしないで、遅くても正しく打つ」です。だいたい、10日から2週間くらい続けると、自分でもタイピングできるようになってきているという自覚がわいてきます。


== 記号の入力や表示に注意する

プログラミングの世界でよく使う文字の入力に注意しましょう。
プログラムを書くときは、空白文字や英数字には半角を使います。また、円記号（ `\` ）、チルダ（ `~` ）、サーカムフレクス（ `^` ）、アクセント（ ``` ）といった記号も使います。 こういった記号のキーの位置や、名前などを覚えておきましょう。

文字の表示では、たとえば半角の円記号（ `\` ）には注意が必要です。多くの人の利用環境ではそのまま半角の円記号（ `\` ）が表示されているでしょうが、英語のキーボードを使っている人や使っているフォントによっては、バックスラッシュ（ `\` ）（スラッシュとは傾きが逆の斜め線）になっていることがあります。このような場合には、この本の半角の円記号の表記をバックスラッシュで読み替えてください。テキストエディターによっては、バックスラッシュを半角の円記号に表示し直す設定もあるので、みなさんの使うエディタの設定方法を確認してみてもよいでしょう。


NOTE: フォント等を調整して、円記号とバックスラッシュの表示を区別してほしいです。


== 毎日使ってエディタの操作に慣れる

慣れないうちは「効率よく使えない」という印象があるかもしれません。でも、それは慣れるまでの少しの間です。いったん慣れたら「マウスはいらないくらい軽快」になります。


使い方を学ぶときは、直感に頼らずにて提供されているチュートリアルを順番にやってみることです。どのエディタもチュートリアルや動画を提供していますし、多くの人がWebサイトで使い方について解説しています。
とくに、入力、削除、カーソルキーに頼らないカーソルの移動、ページの操作、検索、置換、カット＆ペーストといった操作について慣れておくことが、プログラムを作ることに注力する上で大きな違いになってきます。


テキストエディターも道具ですから、使えるようになるにも、便利な使い方を覚えるにも、慣れが肝心です。
どんなことでもよいので、テキストエディターを使って毎日なにか書いてみましょう。毎日使って慣れることが、道具を使いこなせるようになる早道なのです。


.テキストエディターは行番号を表示して使う
* テキストエディターの設定を調べて、行番号を表示するように設定しておきましょう。
* プログラムにエラーが見つかると、行番号つきのエラーメッセージが出力されます。
* 行番号を表示しておくと、エラーの発生箇所を調べやすくなります。


== 演習用ワークスペースを作成する（参考）


NOTE: 下記文章中では、ワークスペースとして `Users\kuboaki\rubybok` といった場所を指定していますが、これは独立した場所で演習留守場合の説明です。 +
みなさんがClassroomからCloneしたリポジトリを使う場合には、cloneしたリポジトリのある場所がワークスペースになります。


この本の演習で使うディレクトリを用意しましょう。演習用のディレクトリを、この本では「ワークスペース」と呼ぶことにします。

=== ホームディレクトリを確認する

エクスプローラーを操作するときには、ファイルを格納する場所を「フォルダ」と呼んでいました。コマンドプロンプトを使うときは「ディレクトリ」と呼びます。

みなさんのログオン名がついたディレクトリを「ホームディレクトリ」といいます。みなさんのホームディレクトリは、 `C:\Users` の下にあります。たとえばわたしの使っているWindows 10では、ログオン名は `kuboaki` ですので、ホームディレクトリは `C:\Users\kuboaki` になります。

あるディレクトリから別のディレクトリやファイルまでを区切り文字（Windowsでは `\` 文字）でつなぐと、目的とするディレクトリやファイルの位置を、ディレクトリ名のつながりで表現できます。このような表現の方法をパス名（PATH名）と呼んでいます。たとえば、 `C:\Users\kuboaki` は、ルートディレクトリからわたしのホームディレクトリまでのパス名による表現です。


.ホームディレクトリの名称
* Windows エクスプローラーを使ってホームディレクトリをみると、 `Users` は `ユーザー` という名前で表示されます。

=== 演習用ディレクトリを作成する


演習用のディレクトリをホームディレクトリの下に作ることにしましょう。

コマンドプロンプトを起動したとき、特別な設定をしていなければ現在のディレクトリ（カレントディレクトリ）は、ホームディレクトリになっています。わたしの場合 `C:\Users\kuboaki` です。環境によってはホームディレクトリとログイン時のディレクトリが異なることもあります。そのときは、状況に合わせてディレクトリを移動したり、自分の環境に合わせて説明を読み替えたりしてください。


ホームディレクトリに移動するには `cd` コマンドを使います。`cd` は、カレントディレクトリから別のディレクトリへ移動するコマンドです。
Windowsの場合は、ドライブを変更したいときはドライブ名を入力します（ <<goto_home_dir>> ）。

[[goto_home_dir]]
.【端末】ホームディレクトリへ移動する
[example]
--
[source,console]
----
Z:\documents>C:            # <1>
C:\Windows>cd \Users\kuboaki  # <2>
C:\\Users\kuboaki>
----
<1> Zドライブの `documents` ディレクトリにいて、ドライブをCドライブに変更した。
<2> Cドライブでは `Windows` ディレクトリにいたので、 `\Users\kuboaki` （作者のホームディレクトリ）へ移動した。
--

.引数なしの `cd` コマンドの働き
* Macのターミナルで使われているシェル（Bashやzsh）では、引数なしで `cd` コマンドを実行するとホームディレクトリへ移動します。


次に演習用ディレクトリを作成しましょう。ディレクトリの作成には `mkdir` コマンドを使います。 `rubybook` を、この本の演習用ディレクトリの名前とします（ <<make_work_dir>> ）。

[[make_work_dir]]
.【端末】演習用ディレクトリを作成する
[example]
--
[source,console]
----
C:\Users\kuboaki>mkdir rubybook  # <1>
----
<1>  演習用ディレクトリ `rubybook` を作成した。
--

[TIP]
--
演習用ディレクトリの場所や名前は別のものでもかまいません。たとえば、ログイン名やパス名に日本語が使われていると、コマンドラインから日本語を入力することが多くなり煩わしいでしょう。そのようなときは、別の場所を使いましょう。
--

[IMPORTANT]
--
ルートディレクトリから演習用のディレクトリまでのパス名のどこかに空白文字（スペース）が含まれていると、ディレクトリ名の入力がうまくできなかったり、プログラムが動かなくなることがあります。演習に使うパスには、スペースを使っていないディレクトリを選ぶようにしましょう。
--

演習用ディレクトリが作成できているか確認しましょう。 `dir` コマンドは、引数で指定したディレクトリ内のファイルやディレクトリのリストを表示するコマンドです。引数にいま作成したディレクトリ名を指定して実行してみましょう（ <<print_work_dir_01>> ）。

TIP:  コマンド名などの後ろに続けて書く文字の並びを引数（ひきすう）といいます。パラメータと呼ぶときもあります。 

[[print_work_dir_01]]
.【端末】演習用ディレクトリの中身を確認する
[example]
--
[source,console]
----
C:\Users\kuboaki>dir rubybook
 ドライブ C のボリューム ラベルがありません。
 ボリューム シリアル番号は 1808-7211 です

 C:\Users\kuboaki\rubybook のディレクトリ   # <1>

2020/04/21  17:01    <DIR>          .
2020/04/21  17:01    <DIR>          ..
               0 個のファイル                   0 バイト
               2 個のディレクトリ  205,166,583,808 バイトの空き領域

C:\Users\kuboaki>
----
<1> 表示しているディレクトリのパス名が表示されている。
--

まだ、何も作成していないので、このディレクトリにはファイルがありませんね。

`dir` コマンドの引数を省略すると、現在のディレクトリの中身を表示します（ <<print_work_dir_02>> ）。

[[print_work_dir_02]]
.【端末】 `dir` コマンドを引数なしで実行する
[example]
--
[source,console]
----
C:\Users\kuboaki>dir    # <1>
 ドライブ C のボリューム ラベルがありません。
 ボリューム シリアル番号は 1808-7211 です

 C:\Users\kuboaki のディレクトリ    # <2>

2020/04/21  17:01    <DIR>          .
2020/04/21  17:01    <DIR>          ..
2020/03/12  07:13    <DIR>          Contacts
2020/03/30  04:28    <DIR>          Desktop
2019/08/09  14:53    <DIR>          Documents
（略）
2020/04/21  17:01    <DIR>          rubybook # <3>
（略）
----
<1> `dir` コマンドの引数を省略して実行した。
<2> 現在のディレクトリ名前になっている。
<3> 作成したワークスペースが確認できる。
--

これで、演習用のディレクトリが作成できました。今後はこのディレクトリを指して「ワークスペース」と呼ぶことにしましょう。

