:linkcss:
:stylesdir: css
:stylesheet: mystyle.css
:twoinches: width='360'
:full-width: width='100%'
:three-quarters-width: width='75%'
:two-thirds-width: width='66%'
:half-width: width='50%'
:half-size:
:one-thirds-width: width='33%'
:one-quarters-width: width='25%'
:thumbnail: width='60'
:imagesdir: images
:sourcesdir: codes
:icons: font
:hide-uri-scheme!:
:figure-caption: 図
:example-caption: リスト
:table-caption: 表
:appendix-caption: 付録
:xrefstyle: short
:section-refsig:
:chapter-refsig:

[[setup_text_editor]]
= テキストエディターを用意する

プログラミングは、多くの文字を打ち込む作業です。そんなプログラマにとって、プログラムを入力するために使う道具は、料理人の包丁、美容師のハサミにも匹敵する重要な道具です。
そのため、ほとんどのプログラマは、プログラムを書くのに便利な機能を持ったお気に入りのアプリケーションを使います。そのようなアプリケーションは、テキストエディターとかプログラミングエディターと呼ばれています（短くエディターと呼ぶことが多いです）。

みなさんが、まだプログラミング用のテキストエディターを用意していないようなら、ここで準備しておきましょう。


== テキストエディターはプログラミングに必須

プログラミングは、通常の文章の入力に比べると、たくさんのカーソルの移動、テキストの一部の切り貼り（カット＆ペースト）、検索や置換を使います。
そのため、入力や操作の軽快さが重要になってきます。
文字列の入力やカーソルの移動がスムーズにできないと、プログラムを作っているときに思考のリズムが乱れてしまうからです。

Windowsのメモ帳やMacのテキストエディットでも、プログラムを編集しようと思えばできます。
しかし、プログラムの予約語の誤りや構文の小さなミスを発見するのにも、テキストエディターを使うときよりも時間がかかってしまうでしょう。
つまり、プログラムの編集にはあまり適していないのです。

一方、テキストエディターは、プログラミング向けに <<editor_functions>> のような機能を提供しています。


[[editor_functions]]
.プログラム開発に使うテキストエディターの機能
[example]
--
* プログラム言語の種類による予約語の色分け（シンタックスハイライト）
* 入力の補完（コンプリーション）
* 外部アプリケーションとの連携
* 自動的に字下げを支援する（オートインデント）
* 多数のキーボードショートカットによるマウス利用の回避
--

このほかにも、プログラマの作業に向くよう、軽快な入力とよく使う操作を簡便に利用する工夫を数多く提供しています。


== 自分が使うテキストエディターを決めよう

もし、すでにインストールされていたり使っているエディターがある人はそれを使うとよいでしょう。
まだ定まったテキストエディターを持っていない人は、この機会にインストールして、使えるようになってしまいましょう。

まだ決まったエディターを使っていない人は、身近な友人や同僚が使っているものを選ぶとよいでしょう。
無料で使えるものから、私がおすすめするエディターを <<recommended_editors>> に挙げておきます。


[[recommended_editors]]
.おすすめのテキストエディター
[cols="25%,75%"]
|===
2+h| Windows、Mac用、linux用
| Visual Studio Code | `https://azure.microsoft.com/ja-jp/products/visual-studio-code/`
| Vim | `http://www.vim.org/`
| Emacs | `http://www.gnu.org/software/emacs/emacs.html`
2+h| Windows、Mac用
| Brackets | `http://brackets.io/`
2+h| Windows用
| Notepad++ | `https://notepad-plus-plus.org/`
| xyzzy | `https://xyzzy-022.github.io/`
2+h| Mac用
| CotEditor | `https://apps.apple.com/app/coteditor/`
|===

それぞれのエディターの導入方法、機能、使い方については、Webサイトやその他のページを参照してください。

ところで、WindowsでもMacでも使えるエディターが多いのに気づいたでしょうか。こういうエディターならば、PCからMacに乗り換えたときでも同じエディターが使えますね。


== テキストエディターに慣れておこう

プログラミングだけでなく、アプリケーションやルーツの設定、文書の作成においても、テキストファイルを編集するのが基本です。
そのときは、みなさんが選んだテキストエディターを使って編集することになるでしょう。

みなさんがどのエディターを選ぶとしても、最初に注意しておくことがあります。それは、テキストエディターは「GUIアプリケーションではない」ということです。
基本的にキーボードからのキー操作によって使うものです。
このことは、普段はアプリケーションをマウスで操作している人、とりわけタイピングに慣れていない人にってとっては、最初は煩わしいこと感じるでしょう。
それだけに、普段から使って慣れておくことが大切です。

== タイピングに慣れておこう

ある大学の講義でプログラミング演習をやったときのことです。演習についてこれない学生のほとんどは、やっている内容がわからないのではなく、それ以前に入力が遅くてついてこれないのだということがわかりました。

そこで、タイピングが不得手な人は、学習と並行してタイピングを練習することを強くお勧めします。
タイピングの練習についてはWebサイトやアプリケーションがたくさんあるので、探してみましょう。
コツは一時期にまとまった時間で練習するのではなく「毎日10分だけ、でも毎日練習する」「指導方法を守ってゆっくりでよいから確実に」「早く打とうとしないで、遅くても正しく打つ」です。だいたい、10日から2週間くらい続けると、自分でもタイピングできるようになってきているという自覚がわいてきます。


== 記号の入力や表示に注意する

プログラミングの世界でよく使う文字の入力に注意しましょう。
プログラムを書くときは、空白文字や英数字には半角を使います。
また、円記号（半角の `￥` ）、チルダ（ `~` ）、サーカムフレクス（ `^` ）、アクセント（ ``` ）といった記号も使います。 こういった記号のキーの位置や、名前などを覚えておきましょう。

文字の表示では、たとえば半角の円記号（半角の `￥` ）には注意が必要です。
多くの人の利用環境ではそのまま半角の円記号が表示されているでしょうが、英語のキーボードを使っている人や使っているフォントによっては、バックスラッシュ（ `\` ）（スラッシュとは傾きが逆の斜め線）になっていることがあります。
このような場合には、円記号の表記をバックスラッシュで読み替えてください。
テキストエディターによっては、バックスラッシュを半角の円記号に表示し直す（あるいはその逆の）設定もあるので、みなさんの使うエディターの設定方法を確認しておくとよいでしょう。


== 毎日使ってエディターの操作に慣れる

慣れないうちは「効率よく使えない」という印象があるかもしれません。でも、それは慣れるまでの少しの間です。いったん慣れたら「マウスはいらないくらい軽快」になります。


操作方法を身につけるときは、直感に頼らずにて提供されているチュートリアルを順番にやってみることです。
どのエディターもチュートリアルや動画を提供していますし、多くの人がWebサイトで使い方について解説しています。
とくに、入力、削除、カーソルキーに頼らないカーソルの移動、ページの操作、検索、置換、カット＆ペーストといった操作について慣れておくことが、プログラムを作ることに注力する上で大きな違いになってきます。


テキストエディターも道具ですから、使えるようになるにも、便利な使い方を覚えるにも、慣れが肝心です。
どんなことでもよいので、テキストエディターを使って毎日なにか書いてみましょう。毎日使って慣れることが、道具を使いこなせるようになる早道なのです。

== 行番号を表示して使う

テキストエディターを使うときは、行番号を表示して使うように設定しておくとよいでしょう。
テキストエディターの設定を調べて、行番号を表示するように設定しておきます。


.行番号を表示しておくと助かること
* プログラムにエラーが見つかると、行番号つきのエラーメッセージが出力されます。
* 行番号を表示しておくと、エラーの発生箇所を調べやすくなります。


== 文字コードに注意する

最近のプログラムやテキストは、文字コードに「BOMなしのUTF-8 （UTF-8Nなどとも書く）」を使うことが多くなりました。
テキストエディターの設定を調べて、新しく作るファイルの文字コードが「BOMなしのUTF-8」になるよう、あらかじめ設定しておきましょう。
